import Head from "next/head";

import Header from "../components/Header";
import LeftHandSide from "../components/LeftHandSide";
import RightHandSide from "../components/RightHandSide";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hola Services</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://scontent.fhan18-1.fna.fbcdn.net/v/t1.15752-9/331391584_868971770994683_923834671532642509_n.png?_nc_cat=108&ccb=1-7&_nc_sid=ae9488&_nc_ohc=Iepe4G33xhwAX-9pnFS&_nc_ht=scontent.fhan18-1.fna&oh=03_AdSSWAFcO9aQNIJpg_HMqb1S6icAeJLXLn5f686YGkInNA&oe=6419A91D"
        />
      </Head>
      <Header isShow={true} />
      <main>
        <LeftHandSide />
        <RightHandSide />
      </main>
    </div>
  );
}
